version: "3"

services:

  frontend:
    build:
      context: ./
      dockerfile: "frontend.Dockerfile"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - api
