version: "3.7"

networks:
  web:
    external: true
  ccs-website:

services:

  app:
    image: ghcr.io/chaostreff-flensburg/ccs-website/frontend:latest
    restart: unless-stopped
    networks:
      - web
      - ccs-website
    labels:
      - traefik.enable=true
      - traefik.http.routers.ccs-website.rule=Host(`ccs.chaostreff-flensburg.de`)
      - traefik.http.routers.ccs-website.entrypoints=websecure
      - traefik.http.routers.ccs-website.tls=true
      - traefik.http.routers.ccs-website.certresolver=le
      - traefik.http.services.ccs-website.loadbalancer.server.port=8080
      - traefik.docker.network=web
